### ISSUE TITLE
以图生图报错

### ISSUE THREAD

**Issue by WindraiteLesd** [sena-nana/nonebot-plugin-novelai#12]
python3.9，插件版本0.5.5，以SD模式进行以图绘图出现如下报错
另外点数模式的配置是否有问题？config文件里仍写着2为无限制，但文档却写着3才是无限制，sd/naifu模式以图绘图能不能忽略点数模式的设置。
[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_novelai.aidraw) failed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\lesd2\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_novelai\aidraw.py", line 86, in aidraw_get
    args.tags = await prepocess_tags(args.tags)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_novelai\utils\prepocess.py", line 6, in prepocess_tags
    tags: str = "".join([i+" " for i in tags])
携带tag时报错：TypeError: sequence item 1: expected str instance, Message found
未携带tag报错：TypeError: sequence item 0: expected str instance, Message found

**Comment by sena-nana** [comment]
去更新，以文档为准，忽略点数模式就是不限制（3）

**Comment by sena-nana** [comment]
0.5.6版本已经解决了这个问题

**Comment by WindraiteLesd** [comment]
> 0.5.6版本已经解决了这个问题

11-28 15:35:31 [ERROR] nonebot | Failed to import "nonebot_plugin_novelai"
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\lesd2\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\LesdNoneBot2\.\bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_novelai\__init__.py", line 2, in <module>
    from .aidraw import AIDRAW
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot_plugin_novelai\aidraw.py", line 20, in <module>
    from .extension.anlas import anlas_check, anlas_set
ModuleNotFoundError: No module named 'nonebot_plugin_novelai.extension'

**Comment by sena-nana** [comment]
你更新一下0.5.7试试，包管理器抽风了打包出了问题

**Comment by WindraiteLesd** [comment]
解决了
但是env里NOVELAI_PAID填3的话没有用，触发指令bot会返回以图生图功能已禁用，得去config.py里改成3

**Comment by sena-nana** [comment]
看看你的env截图，确定是写到了正确的env文件吗

**Comment by WindraiteLesd** [comment]
> 看看你的env截图，确定是写到了正确的env文件吗

![image](https://user-images.githubusercontent.com/104503043/204444947-a933955f-e3d9-4adf-93a2-59e8731726a3.png)

**Comment by sena-nana** [comment]
完整的截图，整个文件的截图，其他的设置有生效吗

**Comment by WindraiteLesd** [comment]
> 

![image](https://user-images.githubusercontent.com/104503043/204445379-315fcf06-7aa8-413a-b3cb-aed8ff4ca59c.png)
![image](https://user-images.githubusercontent.com/104503043/204445449-6e2366cc-df1d-4eec-bac2-fc94c111e702.png)

其他的都生效了，就只有env这里改PAID = 3是没用的，config只改了paid

**Comment by sena-nana** [comment]
如果设置里改可以那就先这样用吧，我这里也想不出为什么。等等看有没有第二例报告

**Comment by Feiyuyu0503** [comment]
我在env里NOVELAI_PAID填3的话也没有用，在代码里改动才生效
