### ISSUE TITLE
[Bug]: 再使用novelai开始绘图的时候报错

### ISSUE THREAD

**Issue by liliosktp** [sena-nana/nonebot-plugin-novelai#25]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项
- [X] 我已使用最新版本测试过，确认问题依旧存在
- [X] 我确定在 GitHub Issues 中没有相同或相似的问题

### 发生错误的版本号

0.5.9

### 问题描述

依照手册上进行了设定并配置了novelai的api等之后

在群内输入.AIDRAW' 或者是召唤的指令  无任何反应

进后台看了一下显示报错

### 如何复现

2. 我的运行环境是……windows 10 IOT
3. 我对BOT使用的指令 .aidraw or 召唤等指令
4. Python版本: 3.9.9
5  Nonebot2版本: 2.0.0rc4
6. 依照开始绘图指令操作了 .AIDRAW' qq群并没有反应 回到主控台有报错

### 日志信息

05-31 21:27:02 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_novelai.aidraw) failed.
Traceback (most recent call last):
  File "C:\littlepaimon\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\LittlePaimon\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "C:\LittlePaimon\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_novelai\aidraw.py", line 115, in aidraw_get
    logger.debug(fifo)
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_novelai\backend\base.py", line 262, in __str__
    return self.__repr__().replace("\n", ";")
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_novelai\backend\base.py", line 258, in __repr__
    + "".join(self.format())
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_novelai\backend\base.py", line 245, in format
    dict_self = dict(self)
  File "C:\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_novelai\backend\base.py", line 242, in __getitem__
    return getattr(self, item)
AttributeError: 'AIDRAW' object has no attribute 'sampler'

**Comment by sena-nana** [comment]
你可以先把aidraw类key里面的sampler删掉，目前并没有使用这个，可能是由于novelai后端并没有初始化这个值导致的。novelai后端已经不再维护，并且非常不建议再使用novelai作为后端，不仅是因为novelai价格昂贵且会封禁bot，而且sd的效果已经远超novelai，相比之下租一个gpu服务器都要更加划算。
我并不能保证这个bug修复以后novelai后端是否能够继续使用，因为我已经没有novelai账号，无法进行调试

**Comment by liliosktp** [comment]
阿解决了 不过产生新的问题  不过既然没有novelai那就结束这个问题了  谢谢帮忙
也考虑去租个gpu 服务器来玩了
